categories:
  - CCP
description: Execute methods on CCP
long_description: List, choose and execute a method on the D4Science CCP platform.
name: ccp_method
owner: m.lettere@gmail.com
homepage_url: https://github.com/dcore94/galaxy-ccp-tools
remote_repository_url: https://github.com/dcore94/galaxy-ccp-tools
