import sys
import time

print("Starting dummy...")
f = open("dummy.out", "w")
f.write("This is some fake output generated by dummy method considering input parameter %s" % sys.argv[1])
f.close()
time.sleep(10)
print("Dummy done!")